.TH PIVEO 1 "September 2026" "Piveo 2.5.8" "User Commands"
.SH NAME
piveo \- application for learning faces, first names and names
.SH SYNOPSIS
.B piveo
.SH DESCRIPTION
.B Piveo
is an educational graphical application for learning and memorizing
faces, first names and names of people.
.SH OPTIONS
Piveo does not currently provide command-line options.
.SH AUTHOR
Piveo was written by Gerard Le Rest.
